// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3imDBHFnFkBfFGk8TCfRT6qURaIGKT4',
    appId: '1:272957114261:web:2d1b781cf9fec3f973589c',
    messagingSenderId: '272957114261',
    projectId: 'dating-app-76639',
    authDomain: 'dating-app-76639.firebaseapp.com',
    storageBucket: 'dating-app-76639.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwYHwkm1Xus3xBd_Z9gWTuHTR794ooIMc',
    appId: '1:272957114261:android:521724a628033b7673589c',
    messagingSenderId: '272957114261',
    projectId: 'dating-app-76639',
    storageBucket: 'dating-app-76639.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQiGIMxyMkUzdWLGI2FjZWecLjs2WrN3s',
    appId: '1:272957114261:ios:0d4971bbe188eeeb73589c',
    messagingSenderId: '272957114261',
    projectId: 'dating-app-76639',
    storageBucket: 'dating-app-76639.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQiGIMxyMkUzdWLGI2FjZWecLjs2WrN3s',
    appId: '1:272957114261:ios:2b342460a72eb59373589c',
    messagingSenderId: '272957114261',
    projectId: 'dating-app-76639',
    storageBucket: 'dating-app-76639.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
